// GitHub Pages only serves static files, so the frontend reads a pre-built
// cache.json (regenerated by a scheduled GitHub Action + build_cache.py)
// instead of calling a live Python backend.
const API_URL = 'cache.json';
const REFRESH_INTERVAL_MS = 5 * 60 * 1000; // re-check the static file every 5 minutes while the page is open

let watchlistData = {};
let stockKeys = [];
let selectedSymbol = null;
let selectedGroup = null;
let groupsMap = {};
let groupLabels = {};

const symbolLabel = document.getElementById('symbolLabel');
const companyNameLabel = document.getElementById('companyNameLabel');
const actionBadge = document.getElementById('actionBadge');
const headline = document.getElementById('headline');
const thesis = document.getElementById('thesis');
const expectedReturn = document.getElementById('expectedReturn');
const confidenceText = document.getElementById('confidenceText');
const riskLevel = document.getElementById('riskLevel');
const scoreValue = document.getElementById('scoreValue');
const scoreRing = document.getElementById('scoreRing');
const weeklyMove = document.getElementById('weeklyMove');
const dailyMove = document.getElementById('dailyMove');
const signalText = document.getElementById('signalText');
const scoreTable = document.getElementById('scoreTable');
const homeGrid = document.getElementById('homeGrid');
const detailTitle = document.getElementById('detailTitle');
const setupTag = document.getElementById('setupTag');
const confidenceTag = document.getElementById('confidenceTag');
const dailyTag = document.getElementById('dailyTag');
const weeklyTag = document.getElementById('weeklyTag');
const dailyTable = document.getElementById('dailyTable');
const weeklyTable = document.getElementById('weeklyTable');
const insightsList = document.getElementById('insightsList');
const statusLine = document.getElementById('statusLine');
const tabNav = document.getElementById('tabNav');
const stockPicker = document.getElementById('stockPicker');

function getActionClass(action) {
  if (action === 'BUY') return 'buy';
  if (action === 'WAIT') return 'wait';
  return 'avoid';
}

function fmtPct(value) {
  const n = Number(value) || 0;
  return `${n > 0 ? '+' : ''}${n.toFixed(1)}%`;
}

// Turns raw score/metric numbers into the human-readable factor rows and
// narrative copy the dashboard shows. All derived purely from live data —
// nothing here is per-symbol hardcoded content anymore.
function buildDerivedFields(stock) {
  const { score, action, risk, confidence, trendStrength, volatility, volPenalty, distanceFromHigh, distanceFromLow, trailingBlocks, cusum, regimeProbabilities, expectedRange } = stock;

  const catalystScore = Math.max(0, Math.min(100, Math.round(50 + (stock.monthlyMove || 0) * 1.5)));
  const trendScore = Math.max(0, Math.min(100, Math.round(50 + trendStrength * 6)));
  const drawdownScore = Math.max(0, Math.min(100, Math.round(100 + distanceFromHigh * 2.5)));
  const momentumScore = Math.max(0, Math.min(100, Math.round(50 + stock.weeklyMove * 2.2)));
  const regimeScore = Math.round((regimeProbabilities.bull || 0) * 100);

  // These four are the ONLY things weighted into the composite score
  // (25% / 20% / 15% / 40%). Volatility and "recent catalyst" are shown
  // below for context but are NOT weighted the same way — see their
  // `weightLabel`/`isPenalty`/`isInfo` flags.
  const metrics = [
    { name: 'Bayesian bull posterior', weightLabel: '40% of score', value: regimeScore, detail: `P(bull)=${(regimeProbabilities.bull * 100).toFixed(0)}% · P(neutral)=${(regimeProbabilities.neutral * 100).toFixed(0)}% · P(bear)=${(regimeProbabilities.bear * 100).toFixed(0)}%` },
    { name: 'Momentum (1W)', weightLabel: '25% of score', value: momentumScore, detail: `Weekly move ${fmtPct(stock.weeklyMove)}` },
    { name: 'Trend (20d vs 50d)', weightLabel: '20% of score', value: trendScore, detail: trendStrength >= 0 ? 'Short-term average above long-term' : 'Short-term average below long-term' },
    { name: 'Distance from high', weightLabel: '15% of score', value: drawdownScore, detail: `${distanceFromHigh.toFixed(1)}% from 3mo high` },
    { name: 'Volatility control', weightLabel: 'direct penalty, not weighted', value: Math.round(volPenalty), isPenalty: true, detail: `${volatility.toFixed(1)}% daily stdev → −${volPenalty.toFixed(1)} pts subtracted from the score` },
    { name: 'Recent catalyst (1M)', weightLabel: 'informational only, not scored', value: catalystScore, isInfo: true, detail: `Monthly move ${fmtPct(stock.monthlyMove)}` }
  ];

  const setupTagText = action === 'BUY' ? 'Meaningful setup' : action === 'WAIT' ? 'Developing setup' : 'Weak setup';
  const confidenceTagText = `${confidence} conviction`;
  const dayStatus = stock.dailyMove > 0.15 ? 'Positive' : stock.dailyMove < -0.15 ? 'Negative' : 'Neutral';
  const weekStatus = stock.weeklyMove > 3 ? 'Uptrend' : stock.weeklyMove < -3 ? 'Downtrend' : 'Stable';

  const expectedLow = expectedRange.low;
  const expectedHigh = expectedRange.high;
  const expectedReturnText = `${expectedLow > 0 ? '+' : ''}${expectedLow}% to ${expectedHigh > 0 ? '+' : ''}${expectedHigh}%`;

  const headlineText =
    action === 'BUY' ? 'Strong positive setup' : action === 'WAIT' ? 'Promising but not yet ideal' : 'Do not force the entry';

  const cusumPhrase =
    cusum.status === 'upside_shift'
      ? 'CUSUM has detected a statistically persistent upward shift versus its own recent baseline (not just one good day).'
      : cusum.status === 'downside_shift'
      ? 'CUSUM has detected a statistically persistent downward shift versus its own recent baseline (not just one bad day).'
      : 'CUSUM has not detected a persistent regime shift — recent behavior is still within normal noise around baseline.';

  const thesisText =
    action === 'BUY'
      ? `${stock.symbol} is showing constructive momentum (${fmtPct(stock.weeklyMove)} this week), a Bayesian bull-regime posterior of ${(regimeProbabilities.bull * 100).toFixed(0)}%, and volatility staying in check. ${cusumPhrase}`
      : action === 'WAIT'
      ? `${stock.symbol}'s signals are mixed — Bayesian posterior favors ${Object.entries(regimeProbabilities).sort((a, b) => b[1] - a[1])[0][0]} at ${(Math.max(...Object.values(regimeProbabilities)) * 100).toFixed(0)}%, but not enough conviction to size in aggressively. ${cusumPhrase}`
      : `${stock.symbol} is underperforming on momentum and trend right now (${fmtPct(stock.weeklyMove)} this week) with a Bayesian bull posterior of only ${(regimeProbabilities.bull * 100).toFixed(0)}%. ${cusumPhrase}`;

  const insights = [
    `Bayesian regime posterior (uniform prior, updated on recent daily returns): bull ${(regimeProbabilities.bull * 100).toFixed(0)}%, neutral ${(regimeProbabilities.neutral * 100).toFixed(0)}%, bear ${(regimeProbabilities.bear * 100).toFixed(0)}%.`,
    `CUSUM regime test: ${cusum.status.replace('_', ' ')} (upper stat ${cusum.upperStat}, lower stat ${cusum.lowerStat}, threshold ±${cusum.threshold} vs its own baseline mean ${cusum.baselineMean}%/day).`,
    `Signal range is a ${expectedRange.horizonTradingDays}-trading-day (~1 month) forward projection using ${stock.symbol}'s own historical daily-return mean and volatility (random-walk ±1 standard deviation) — not derived from the score. Center estimate is ${fmtPct(expectedRange.projectedMean)}; this is a statistical range, not a forecast of what will actually happen.`,
    `Price is ${Math.abs(distanceFromHigh).toFixed(1)}% off its 3-month high and ${distanceFromLow.toFixed(1)}% above its 3-month low — ${distanceFromHigh > -3 ? 'near the top of its recent range.' : 'giving some room before it is stretched.'}`,
    `Daily volatility is running at ${volatility.toFixed(1)}%, which is why the tool flags this as ${risk.toLowerCase()} risk.`
  ];

  return {
    metrics,
    setupTag: setupTagText,
    confidenceTag: confidenceTagText,
    dayStatus,
    weekStatus,
    expectedReturn: expectedReturnText,
    headline: headlineText,
    thesis: thesisText,
    insights,
    weeklyTableRows: trailingBlocks
      .map((move, i) => [`Week ${i + 1} (of last 28 trading days)`, fmtPct(move)])
      .concat([['Regime (heuristic)', weekStatus]]),
    dailyTableRows: [
      ['Price', `$${stock.price.toFixed(2)}`],
      ['1D', fmtPct(stock.dailyMove)],
      ['1W', fmtPct(stock.weeklyMove)],
      ['1M', fmtPct(stock.monthlyMove)],
      ['6M', fmtPct(stock.sixMonthMove)],
      ['YTD', fmtPct(stock.ytdMove)],
      ['Trend', trendStrength >= 0 ? 'Bullish' : 'Bearish'],
      ['CUSUM status', cusum.status.replace('_', ' ')]
    ]
  };
}

function renderHomeGrid() {
  homeGrid.innerHTML = Object.keys(groupsMap)
    .map((group) => {
      const label = groupLabels[group] || group;
      const visibleKeys = stockKeys.filter((symbol) => watchlistData[symbol].group === group);
      if (visibleKeys.length === 0) return '';

      const cards = visibleKeys
        .map((symbol) => {
          const data = watchlistData[symbol];
          return `
            <button class="watch-card" data-symbol="${symbol}" type="button">
              <div class="watch-card-top">
                <div>
                  <strong>${data.symbol}</strong>
                  <div class="company-name">${data.companyName || ''}</div>
                  <small>$${data.price.toFixed(2)}</small>
                </div>
                <span class="mini-action ${getActionClass(data.action)}">${data.action}</span>
              </div>
              <div class="meta">
                <span>1D ${fmtPct(data.dailyMove)}</span>
                <span>1W ${fmtPct(data.weeklyMove)}</span>
              </div>
            </button>
          `;
        })
        .join('');

      return `
        <div class="home-group">
          <h4 class="home-group-title">${label} <span class="home-group-count">(${visibleKeys.length})</span></h4>
          <div class="home-group-grid">${cards}</div>
        </div>
      `;
    })
    .join('');

  homeGrid.querySelectorAll('.watch-card').forEach((button) => {
    button.addEventListener('click', () => {
      selectedSymbol = button.dataset.symbol;
      switchTab('analysis');
      render();
    });
  });
}

function switchTab(tabName) {
  document.querySelectorAll('.tab-page').forEach((page) => {
    page.classList.toggle('active', page.id === `tab-${tabName}`);
  });
  if (tabNav) {
    tabNav.querySelectorAll('.tab-link').forEach((tab) => {
      tab.classList.toggle('active', tab.dataset.tab === tabName);
    });
  }
}

function setupTabNav() {
  if (!tabNav) return;
  tabNav.querySelectorAll('.tab-link').forEach((tab) => {
    tab.addEventListener('click', () => switchTab(tab.dataset.tab));
  });
}

function renderStockPicker() {
  if (!stockPicker) return;

  const optionsHtml = Object.entries(groupsMap)
    .map(([group, symbols]) => {
      const label = groupLabels[group] || (group.charAt(0).toUpperCase() + group.slice(1));
      const opts = symbols
        .filter((symbol) => watchlistData[symbol])
        .map((symbol) => {
          const name = watchlistData[symbol].companyName;
          const optionLabel = name ? `${symbol} — ${name}` : symbol;
          return `<option value="${symbol}" ${symbol === selectedSymbol ? 'selected' : ''}>${optionLabel}</option>`;
        })
        .join('');
      return `<optgroup label="${label}">${opts}</optgroup>`;
    })
    .join('');

  stockPicker.innerHTML = optionsHtml;
  stockPicker.value = selectedSymbol;
}

function setupStockPicker() {
  if (!stockPicker) return;
  stockPicker.addEventListener('change', () => {
    selectedSymbol = stockPicker.value;
    switchTab('analysis');
    render();
  });
}

function renderTable(metrics) {
  scoreTable.innerHTML = `
    <thead>
      <tr>
        <th>Factor</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      ${metrics
        .map((metric) => {
          const barWidth = metric.isPenalty ? Math.min(100, (metric.value / 30) * 100) : metric.value;
          const barClass = metric.isPenalty ? 'metric-fill penalty' : metric.isInfo ? 'metric-fill info' : 'metric-fill';
          const scoreLabel = metric.isPenalty ? `−${metric.value} pts` : metric.isInfo ? `${metric.value}/100 (not scored)` : `${metric.value}/100`;
          return `
            <tr>
              <td>
                <div class="metric-name">${metric.name}</div>
                <div class="metric-weight">${metric.weightLabel || ''}</div>
                <div>${metric.detail}</div>
              </td>
              <td>
                <div>${scoreLabel}</div>
                <div class="metric-bar"><span class="${barClass}" style="width: ${barWidth}%"></span></div>
              </td>
            </tr>
          `;
        })
        .join('')}
    </tbody>
  `;
}

function renderMiniTable(target, rows) {
  target.innerHTML = `
    <tbody>
      ${rows.map(([label, value]) => `<tr><td>${label}</td><td>${value}</td></tr>`).join('')}
    </tbody>
  `;
}

function renderInsights(list) {
  insightsList.innerHTML = list.map((item) => `<li>${item}</li>`).join('');
}

function render() {
  const data = watchlistData[selectedSymbol];
  if (!data) return;

  const derived = buildDerivedFields(data);

  symbolLabel.textContent = data.symbol;
  if (companyNameLabel) companyNameLabel.textContent = data.companyName || '';
  actionBadge.textContent = data.action;
  actionBadge.className = `status-badge ${getActionClass(data.action)}`;
  headline.textContent = derived.headline;
  thesis.textContent = derived.thesis;
  expectedReturn.textContent = derived.expectedReturn;
  confidenceText.textContent = data.confidence;
  riskLevel.textContent = data.risk;
  scoreValue.textContent = data.score;
  scoreRing.style.setProperty('--progress', `${data.score * 3.6}deg`);
  weeklyMove.textContent = fmtPct(data.weeklyMove);
  dailyMove.textContent = fmtPct(data.dailyMove);
  signalText.textContent = data.action;
  detailTitle.textContent = data.symbol;
  setupTag.textContent = derived.setupTag;
  confidenceTag.textContent = derived.confidenceTag;
  dailyTag.textContent = derived.dayStatus;
  dailyTag.className = `pill ${derived.dayStatus === 'Positive' ? 'success' : derived.dayStatus === 'Neutral' ? 'neutral' : 'warning'}`;
  weeklyTag.textContent = derived.weekStatus;
  weeklyTag.className = `pill ${derived.weekStatus === 'Uptrend' ? 'accent' : derived.weekStatus === 'Stable' ? 'neutral' : 'warning'}`;

  renderTable(derived.metrics);
  renderMiniTable(dailyTable, derived.dailyTableRows);
  renderMiniTable(weeklyTable, derived.weeklyTableRows);
  renderInsights(derived.insights);
  renderHomeGrid();
  renderStockPicker();
}

function setStatus(message, isError) {
  if (!statusLine) return;
  statusLine.textContent = message;
  statusLine.style.color = isError ? '#d65145' : '';
}

async function loadWatchlist() {
  setStatus('Refreshing live data…', false);
  try {
    const res = await fetch(API_URL, { cache: 'no-store' });
    if (!res.ok) throw new Error(`Server responded ${res.status}`);
    const payload = await res.json();

    watchlistData = {};
    Object.entries(payload.stocks).forEach(([symbol, stock]) => {
      if (!stock.error) watchlistData[symbol] = stock;
    });
    stockKeys = Object.keys(watchlistData);
    groupsMap = payload.groups || groupsMap;
    groupLabels = payload.groupLabels || groupLabels;

    if (stockKeys.length === 0) {
      setStatus('No data available — cache.json is missing or empty.', true);
      return;
    }

    if (!selectedGroup || !groupsMap[selectedGroup]) {
      selectedGroup = Object.keys(groupsMap)[0];
    }

    if (!selectedSymbol || !watchlistData[selectedSymbol]) {
      selectedSymbol = stockKeys.find((s) => watchlistData[s].group === selectedGroup) || stockKeys[0];
    }

    const updated = new Date(payload.generatedAt * 1000);
    setStatus(`Live data as of ${updated.toLocaleTimeString()} on ${updated.toLocaleDateString()}`, false);

    render();
  } catch (err) {
    setStatus(`Could not load cache.json (${err.message}). It may still be generating — try again shortly.`, true);
  }
}

loadWatchlist();
setupTabNav();
setupStockPicker();
setInterval(loadWatchlist, REFRESH_INTERVAL_MS);
